routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'role:admin']], function () {
    #dd(auth()->user());
    Route::resource('groups', 'GroupsController');
    Route::resource('content', 'ContentController');
    Route::post('content/add', 'ContentController@add');
    Route::get('content/redirect/{id}', 'ContentController@redirect');
    Route::resource('feeds', 'FeedsController');
    Route::resource('queue', 'QueueController');
    Route::any('queue/listings/{type}', 'QueueController@listings');
    Route::post('queue/move/{id}', 'QueueController@move');
    Route::resource('analytics', 'AnalyticsController');
    Route::resource('schedule', 'ScheduleController');
    Route::resource('history', 'HistoryController');
    Route::resource('clients', 'ClientsController');
    Route::get('/uploads/{thumb?}', 'UploadController@getUpload')->where('thumb', '.*');
    Route::post('/upload', 'UploadController@postUpload');
    Route::get('/groups-list', 'GroupsController@getList');
    Route::get('/social-accounts-list', 'SocialController@getList');
    Route::get('/drafts', 'ContentController@getDrafts');
    Route::post('/link-preview', 'ContentController@postLinkPreview');
    Route::resource('review', 'ReviewController');
});

Route::group(['middleware' => ['auth']], function () {
  Route::get('/uploads/{thumb?}', 'UploadController@getUpload')->where('thumb', '.*');
  Route::post('/upload', 'UploadController@postUpload');
});

Route::group(['middleware' => ['auth', 'role:client']], function () {
  Route::get('/client', function () {
      return redirect('social-accounts');
  });
});

Route::group(['prefix' => 'client', 'middleware' => ['auth', 'role:client']], function()
{
    Route::resource('review', 'Client\ReviewController');
});

Route::group(['middleware' => ['auth']], function () {
  Route::resource('settings', 'SettingsController');
  Route::post('/api/upload', 'UploadController@postUpload');
  Route::resource('social-accounts', 'SocialController');
});

Route::get('/twitter/login', 'Social\TwitterController@login')->name('twitter.login');
Route::get('/twitter/callback', 'Social\TwitterController@callback')->name('twitter.callback');
Route::get('/twitter/error', 'Social\TwitterController@error')->name('twitter.error');
Route::get('/twitter/logout', 'Social\TwitterController@logout')->name('twitter.logout');

Route::get('/instagram/checkpoint', 'Social\InstagramController@getCheckpoint')->name('instagram.checkpoint');
Route::post('/instagram/checkpoint', 'Social\InstagramController@postCheckpoint')->name('instagram.post-checkpoint');
Route::resource('instagram', 'Social\InstagramController');

Route::get('/facebook/profile', 'Social\FacebookController@profile')->name('facebook.profile');
Route::get('/facebook/pages', 'Social\FacebookController@pages')->name('facebook.pages');
Route::get('/facebook/groups', 'Social\FacebookController@groups')->name('facebook.groups');
Route::get('/facebook/select/{type}/{fid}', 'Social\FacebookController@select')->name('facebook.select');
Route::get('/facebook/callback', 'Social\FacebookController@callback')->name('facebook.callback');
Route::get('/facebook/choice', 'Social\FacebookController@choice')->name('facebook.choice');
Route::get('/facebook/preselect', 'Social\FacebookController@preSelect')->name('facebook.preselect');
Route::get('/facebook/preselect/{user_id}/{select}', 'Social\FacebookController@preSelectById')->name('facebook.preselect');


Route::get('/install', 'Install\InstallController@index');
Route::get('/install/create', 'Install\InstallController@create'); // private use only
Route::get('/install/update', 'Install\InstallController@createUpdate'); // private use only
Route::get('/install/admin', 'Install\InstallController@admin');
Route::get('/install/finish', 'Install\InstallController@finish');
Route::post('/install', 'Install\InstallController@postIndex');
Route::post('/install/admin', 'Install\InstallController@postAdmin');
Route::post('/install/finish', 'Install\InstallController@postFinish');
Route::get('/install/upgrade', 'Install\InstallController@upgrade');

Route::get('/debug/phpinfo', 'DebugController@phpinfo');
Route::get('/debug/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
Route::get('/debug/cron', 'DebugController@cron');

/**
 * Teamwork routes
 */
Route::group(['prefix' => 'teams', 'namespace' => 'Teamwork'], function()
{
    Route::get('/', 'TeamController@index')->name('teams.index');
    Route::get('create', 'TeamController@create')->name('teams.create');
    Route::post('teams', 'TeamController@store')->name('teams.store');
    Route::get('edit/{id}', 'TeamController@edit')->name('teams.edit');
    Route::put('edit/{id}', 'TeamController@update')->name('teams.update');
    Route::delete('destroy/{id}', 'TeamController@destroy')->name('teams.destroy');
    Route::get('switch/{id}', 'TeamController@switchTeam')->name('teams.switch');

    Route::get('members/{id}', 'TeamMemberController@show')->name('teams.members.show');
    Route::get('members/resend/{invite_id}', 'TeamMemberController@resendInvite')->name('teams.members.resend_invite');
    Route::post('members/{id}', 'TeamMemberController@invite')->name('teams.members.invite');
    Route::delete('members/{id}/{user_id}', 'TeamMemberController@destroy')->name('teams.members.destroy');

    Route::get('accept/{token}', 'AuthController@acceptInvite')->name('teams.accept_invite');
});

app/Http/Controllers/ContentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Post;
use App\Models\ScheduledPost;
use App\Models\SocialAccount;
use App\Models\Group;
use Artisan;
use Carbon\Carbon;
use Dusterio\LinkPreview\Client;
use Log;

class ContentController extends Controller
{
    /**
     * Display a listing of the resource.
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $data = [];
        /*$posts = ScheduledPost::orderByRaw('GREATEST(
          COALESCE(scheduled_at, 0),
          COALESCE(queued_for, 0)
        ) DESC');*/
        $posts = ScheduledPost::orderBy('created_at', 'DESC');
        if($request->get('social_account_id'))
            $posts = $posts->where('social_account_id', $request->get('social_account_id'));
        $posts = $posts->where('active', 1);
        $posts = $posts->paginate(50);

        $data['posts'] = $posts;
        $groups = Group::pluck('name', 'id')->prepend('Choose something…', '');
        $data['group'] = $groups;
        $data['social_accounts'] = SocialAccount::pluck('label', 'id')->prepend('-- SELECT --', '');


        return view('content.index', $data);
    }

    public function postLinkPreview(Request $request)
    {
      $url = $request->get('url');
      return ['status' => true, 'url' => $url, 'preview' => $this->_getLinkPreview($request->get('url'))];
    }

    private function _getLinkPreview($url) {
      $preview = [];
      try {
          $previewClient = new Client($url);
          $preview = $previewClient->getPreview('general');
          $url = $previewClient->getUrl();
          $preview = $preview->toArray();
          $preview['url'] = $url->getHost();
          $brevity = new \Kylewm\Brevity\Brevity();
          $preview['description'] = $brevity->shorten($preview['description']);
      } catch(\Exception $e) {
        Log::info($e->getMessage());
      }
      return $preview;
    }

    public function getDrafts()
    {
        //
        $posts = Post::where('is_draft', true)->orderBy('created_at', 'DESC')->paginate(15);
        return view('content.drafts', ['posts' => $posts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $social_accounts = SocialAccount::orderBy('created_at', 'DESC')->get();
        $groups = Group::orderBy('created_at', 'DESC')->get();

        return view('content.create', ['social_accounts' => $social_accounts, 'groups' => $groups]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if($request->get('scheduled_at') && $request->get('scheduled_at') != 'NOW') {
          $now = Carbon::now();
          $now = $now->addMinute();
          if($now->gt(Carbon::createFromTimestamp(strtotime($request->get('scheduled_at'))))) {
            return response()->json(['error' => "Error: The date/time is in the past"], 500);
          }
        }
        $social_accounts = $request->get('social_accounts');
        $files = collect($request->get('files'));
        $files->transform(function ($item, $key) {
            $row = $item;
            $row['id'] = $item['id'];
            $row['name'] = $item['name'];
            $row['size'] = $item['size'];
            $row['progress'] = 100;
            $row['success'] = true;
            $row['type'] = $item['type'];
            $row['path'] = $item['response']['path'];
            $row['thumb'] = $item['response']['thumb'];
            $row['media_type'] = $item['response']['media_type'];
            return $row;
        });

        $post = new Post();
        $post->message = $request->get('message');
        if($request->get('scheduled_at')) {
          $post->scheduled_at = strtotime($request->get('scheduled_at'));
        }

        $post->files = $files;
        $post->groups = implode(",", $request->get('groups'));
        $post->fine_tune = $request->get('fine_tune');
        $post->is_draft = $request->get('is_draft');
        $post->requires_approval = $request->get('requires_approval');
        $post->social_account_list = collect($request->get('social_accounts'))->where('active', true)->pluck('id');
        $post->save();

        if(!$post->scheduled_at && !$post->is_draft) {
          $post->position = $post->id;
          $post->save();
        }

        foreach($social_accounts as $social_account) {
          if(!isset($social_account['active']) || !$social_account['active'])
            continue;
          $scheduled_post = new ScheduledPost();
          $scheduled_post->post_id = $post->id;
          $scheduled_post->message = $request->get('message');
          $scheduled_post->social_account_id = $social_account['id'];
          $scheduled_post->files = $post->files;
          $scheduled_post->scheduled_at = $post->scheduled_at;
          $scheduled_post->active = true;

          #$this->_getLinkPreview($request->get('url'));

          $scheduled_post->save();
        }

        Artisan::call('warbler:schedule_queue');

        return ['status' => true, 'post' => $post];
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        //
        $post = Post::with(['scheduled_posts', 'scheduled_posts.social_account'])->find($id);
        #dd($post->scheduled_posts->toArray());
        $social_accounts = SocialAccount::orderBy('created_at', 'DESC')->get();
        $groups = Group::orderBy('created_at', 'DESC')->get();

        return view('content.create', ['post' => $post, 'social_accounts' => $social_accounts, 'groups' => $groups]);

    }

    public function add(Request $request)
    {
        $social_account_id = $request->get('social_account_id');
        $post_id = $request->get('post_id');

        $post = Post::with('scheduled_posts')->find($post_id);
        $scheduled_post = ScheduledPost::firstOrCreate(['post_id' => $post->id, 'social_account_id' => $social_account_id]);
        if($scheduled_post->wasRecentlyCreated) {
          $scheduled_post->active = true;
          $scheduled_post->message = $post->message;
          $scheduled_post->files = $post->files;
          $scheduled_post->scheduled_at = $post->scheduled_at;
          $scheduled_post->save();

          $post->social_account_list = array_unique(array_merge($post->social_account_list, [$social_account_id]));
          $post->save();
        }

        $post = Post::with(['scheduled_posts', 'scheduled_posts.social_account'])->find($post_id);
        return ['status' => true, 'post' => $post];
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

      //dd(collect($request->get('social_accounts'))->where('active', true)->pluck('id'));
        //
        /*if !fine_tune
          copy same content to each scheduled_post
        if fine_tune
          unique content
        if draft
          save is_draft = 1, scheduled_at = null
        if add to queue
          save draft = 0*/
        $files = collect($request->get('files'));
        $files = $files->transform(function ($item, $key) {
            $row = $item;
            $row['id'] = $item['id'];
            $row['name'] = $item['name'];
            $row['type'] = $item['type'];
            $row['size'] = $item['size'];
            $row['progress'] = 100;
            $row['success'] = true;
            $row['path'] = $item['response']['path'];
            $row['thumb'] = $item['response']['thumb'];
            $row['media_type'] = $item['response']['media_type'];
            return $row;
        });
        #dd($files);

        $post = Post::with('scheduled_posts')->find($id);
        $post->fine_tune = $request->get('fine_tune');
        $post->is_draft = $request->get('is_draft');
        $post->requires_approval = $request->get('requires_approval');
        $post->message = $request->get('message');
        $post->scheduled_at = (strtotime($request->get('scheduled_at')))?strtotime($request->get('scheduled_at')):NULL;
        $post->files = $files;
        $post->groups = ($request->get('groups'))?implode(",", $request->get('groups')):"";
        $post->social_account_list = collect($request->get('social_accounts'))->where('active', true)->pluck('id');
        $post->save();

        $social_accounts = $request->get('social_accounts');
        $scheduled_posts = collect($request->get('scheduled_posts'));
        foreach($social_accounts as $social_account) {

            $scheduled_post = ScheduledPost::firstOrCreate(['post_id' => $post->id, 'social_account_id' => $social_account['id']]);
            $scheduled_post->active = (bool) $social_account['active'];

            if(!$request->get('fine_tune')) {
                $scheduled_post->message = $request->get('message');
                $scheduled_post->files = $post->files;
                $scheduled_post->scheduled_at = $post->scheduled_at;
            } else {
              $new_post = $scheduled_posts->where('social_account_id', $social_account['id'])->first();
              #print_r($new_post);die();
              if($new_post['files']) {
                $new_post['files'] = collect($new_post['files'])->transform(function ($item, $key) {
                    $row = $item;
                    $row['id'] = $item['id'];

resources/views/content/create.blade.php
@extends('layouts.inner')
@section('title', (isset($post))?'Edit post':'Schedule a new post')

@section('inner')

    <div class="row">
    	<div class="col-md-12">
            @if(!isset($post))

                <ul class="nav nav-pills">
                    <li role="presentation" class="active"><a href="<?= route('content.create') ?>">Create New Post</a></li>
                    <li role="presentation"><a href="/drafts">Drafts</a></li>
                    <?/*<li role="presentation"><a href="<?= route('feeds.index') ?>">RSS Feeds</a></li>*/?>
                </ul>
            @else
                @if(isset($post) && $post->is_draft)
<a href="<?= url('drafts') ?>"><i class="fa fa-chevron-left" aria-hidden="true"></i> Back to drafts</a>
                @else
<a href="<?= route('queue.create') ?>?tab=<?= (!$post->scheduled_at)?'in_queue':'custom_schedule' ?>&accounts=<?= implode(',', $social_accounts->pluck('id')->toArray()) ?>"><i class="fa fa-chevron-left" aria-hidden="true"></i> Back to schedule</a>
                @endif
            @endif
<br />

                  <div class="row">

                              <div class="col-sm-12">
                                  @if(isset($post))
                                    <edit-post :post="{{json_encode($post, JSON_NUMERIC_CHECK)}}" :groups="{{json_encode($groups)}}" :social-accounts="{{json_encode($social_accounts)}}"></edit-post>
                                  @else
                                    <post :groups="{{json_encode($groups)}}" :social-accounts="{{json_encode($social_accounts)}}"></post>
                                  @endif
                              </div>

                    </div>

        </div>

	</div>




@endsection

resources/views/content/drafts.blade.php
@extends('layouts.inner')
@section('title', 'Drafts')

@section('inner')


                <ul class="nav nav-pills">
                    <li role="presentation"><a href="<?= route('content.create') ?>">Create New Post</a></li>
                    <li role="presentation"  class="active"><a href="/drafts">Drafts</a></li>
                </ul>
<br />
<div class="panel panel-default">
    <div class="panel-body">
                  <div class="row">


                              <div class="col-sm-12">
                  <h4>Draft Posts</h4>

              <p>Drafts are posts that have not been scheduled yet.</p>

              <? if(count($posts) == 0) : ?>
              <br />
              <div class="alert alert-warning" role="alert">
                <strong>Notice:</strong> You have no draft posts.
              </div>
              <? else: ?>


              <table class="table">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Message</th>
                      <th>Creation date</th>
                      <th></th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    <? foreach($posts as $post) : ?>
                    <tr>
                      <td>#<?= $post->id ?></td>
                      <td><?= str_limit($post->message, 20) ?></td>
                      <td><?= $post->created_at->diffForHumans() ?></td>
                      <td><a href="/content/<?= $post->id ?>/edit">Edit/Publish</a></td>
                      <td><a class="delete-confirm" data-url="/content/<?= $post->id ?>" data-text="Are you sure you want to post #<?= $post->id ?>?" href="#" data-id="<?= $post->id ?>">Delete</a></td>
                    </tr>
                    <? endforeach; ?>
                  </tbody>
                </table>

                {{ $posts->links() }}

                <? endif; ?>
        </div>
        </div>
        </div>

	</div>



@endsection

resources/views/content/index.blade.php
@extends('layouts.inner')
@section('title', 'Drafts')

@section('inner')


<ul class="nav nav-pills">
    <li role="presentation"><a href="<?= route('content.create') ?>">Create New Post</a></li>
    <li role="presentation"><a href="/drafts">Drafts</a></li>
</ul>
<br />
<div class="panel panel-default">
    <div class="panel-body">
                  <div class="row">


                              <div class="col-sm-12">

                  <form action="/content" method="GET">
                  <div class="row">
                    <div class="col-sm-6">
                        <h4>Viewing all posts</h4>
                    </div>
                    <div class="col-sm-4">
                      <?= Form::select('social_account_id', $social_accounts, null,  ['class' => 'form-control']); ?>
                    </div>
                    <div class="col-sm-2">
                      <button class="btn btn-default" type="submit">Filter</button>
                    </div>
                  </div>
              </form>
                  <hr />

                  <table class="table">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th></th>
                          <th>Message</th>
                          <th>Scheduled for</th>
                          <th>Status</th>
                          <th>Created</th>
                        </tr>
                      </thead>
                      <tbody>
                        <? foreach($posts as $post) : ?>
                        <tr class="<?= ($post->post_id%2)?'active':'' ?>">
                          <td>#<?= $post->post_id ?></td>
                          <td title="<?= $post->id ?>">
                              <? if($post->social_account) : ?><i class="mdi mdi-<?= $post->social_account->platform ?> <?= $post->social_account->platform ?>"></i><? endif; ?>
                          </td>
                          <td><a href="/content/<?= $post->post_id ?>/edit"><?= str_limit($post->message, 30) ?></a></td>
                          <td><?= ($post->post_date)?$post->post_date->format('jS M H:i'):'-' ?></td>
                          <td><? if($post->status == 'FAILED') : ?><i data-toggle="tooltip" data-placement="top" title="<?= $post->error_log ?>" class="fa fa-exclamation-triangle fa-fw" style="color: #ff0000" aria-hidden="true"></i><? endif ?> <?= $post->status_text ?> <? if($post->status == 'SENT') : ?><a href="/content/redirect/<?= $post->id ?>" target="_blank"><i class="fa fa-external-link fa-fw" aria-hidden="true"></i></a><? endif ?></td>
                          <td><?= ($post->created_at)?$post->created_at->diffForHumans():'-' ?></td>
                        </tr>
                        <? endforeach; ?>
                      </tbody>
                    </table>


                {{ $posts->appends($_GET)->links() }}
        </div>
        </div>
        </div>

	</div>



@endsection