routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'role:admin']], function () {
    #dd(auth()->user());
    Route::resource('groups', 'GroupsController');
    Route::resource('content', 'ContentController');
    Route::post('content/add', 'ContentController@add');
    Route::get('content/redirect/{id}', 'ContentController@redirect');
    Route::resource('feeds', 'FeedsController');
    Route::resource('queue', 'QueueController');
    Route::any('queue/listings/{type}', 'QueueController@listings');
    Route::post('queue/move/{id}', 'QueueController@move');
    Route::resource('analytics', 'AnalyticsController');
    Route::resource('schedule', 'ScheduleController');
    Route::resource('history', 'HistoryController');
    Route::resource('clients', 'ClientsController');
    Route::get('/uploads/{thumb?}', 'UploadController@getUpload')->where('thumb', '.*');
    Route::post('/upload', 'UploadController@postUpload');
    Route::get('/groups-list', 'GroupsController@getList');
    Route::get('/social-accounts-list', 'SocialController@getList');
    Route::get('/drafts', 'ContentController@getDrafts');
    Route::post('/link-preview', 'ContentController@postLinkPreview');
    Route::resource('review', 'ReviewController');
});

Route::group(['middleware' => ['auth']], function () {
  Route::get('/uploads/{thumb?}', 'UploadController@getUpload')->where('thumb', '.*');
  Route::post('/upload', 'UploadController@postUpload');
});

Route::group(['middleware' => ['auth', 'role:client']], function () {
  Route::get('/client', function () {
      return redirect('social-accounts');
  });
});

Route::group(['prefix' => 'client', 'middleware' => ['auth', 'role:client']], function()
{
    Route::resource('review', 'Client\ReviewController');
});

Route::group(['middleware' => ['auth']], function () {
  Route::resource('settings', 'SettingsController');
  Route::post('/api/upload', 'UploadController@postUpload');
  Route::resource('social-accounts', 'SocialController');
});

Route::get('/twitter/login', 'Social\TwitterController@login')->name('twitter.login');
Route::get('/twitter/callback', 'Social\TwitterController@callback')->name('twitter.callback');
Route::get('/twitter/error', 'Social\TwitterController@error')->name('twitter.error');
Route::get('/twitter/logout', 'Social\TwitterController@logout')->name('twitter.logout');

Route::get('/instagram/checkpoint', 'Social\InstagramController@getCheckpoint')->name('instagram.checkpoint');
Route::post('/instagram/checkpoint', 'Social\InstagramController@postCheckpoint')->name('instagram.post-checkpoint');
Route::resource('instagram', 'Social\InstagramController');

Route::get('/facebook/profile', 'Social\FacebookController@profile')->name('facebook.profile');
Route::get('/facebook/pages', 'Social\FacebookController@pages')->name('facebook.pages');
Route::get('/facebook/groups', 'Social\FacebookController@groups')->name('facebook.groups');
Route::get('/facebook/select/{type}/{fid}', 'Social\FacebookController@select')->name('facebook.select');
Route::get('/facebook/callback', 'Social\FacebookController@callback')->name('facebook.callback');
Route::get('/facebook/choice', 'Social\FacebookController@choice')->name('facebook.choice');
Route::get('/facebook/preselect', 'Social\FacebookController@preSelect')->name('facebook.preselect');
Route::get('/facebook/preselect/{user_id}/{select}', 'Social\FacebookController@preSelectById')->name('facebook.preselect');


Route::get('/install', 'Install\InstallController@index');
Route::get('/install/create', 'Install\InstallController@create'); // private use only
Route::get('/install/update', 'Install\InstallController@createUpdate'); // private use only
Route::get('/install/admin', 'Install\InstallController@admin');
Route::get('/install/finish', 'Install\InstallController@finish');
Route::post('/install', 'Install\InstallController@postIndex');
Route::post('/install/admin', 'Install\InstallController@postAdmin');
Route::post('/install/finish', 'Install\InstallController@postFinish');
Route::get('/install/upgrade', 'Install\InstallController@upgrade');

Route::get('/debug/phpinfo', 'DebugController@phpinfo');
Route::get('/debug/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
Route::get('/debug/cron', 'DebugController@cron');

/**
 * Teamwork routes
 */
Route::group(['prefix' => 'teams', 'namespace' => 'Teamwork'], function()
{
    Route::get('/', 'TeamController@index')->name('teams.index');
    Route::get('create', 'TeamController@create')->name('teams.create');
    Route::post('teams', 'TeamController@store')->name('teams.store');
    Route::get('edit/{id}', 'TeamController@edit')->name('teams.edit');
    Route::put('edit/{id}', 'TeamController@update')->name('teams.update');
    Route::delete('destroy/{id}', 'TeamController@destroy')->name('teams.destroy');
    Route::get('switch/{id}', 'TeamController@switchTeam')->name('teams.switch');

    Route::get('members/{id}', 'TeamMemberController@show')->name('teams.members.show');
    Route::get('members/resend/{invite_id}', 'TeamMemberController@resendInvite')->name('teams.members.resend_invite');
    Route::post('members/{id}', 'TeamMemberController@invite')->name('teams.members.invite');
    Route::delete('members/{id}/{user_id}', 'TeamMemberController@destroy')->name('teams.members.destroy');

    Route::get('accept/{token}', 'AuthController@acceptInvite')->name('teams.accept_invite');
});

app/Http/Controllers/Client/HomeController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use Storage;
use Image;
use Response;
use Redirect;
use Twitter;
use Session;
use Mail;
use App\Models\Group;
use App\Models\SocialAccount;
use App\Http\Requests\StoreInstagram;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Crypt;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        ##$this->middleware('auth');
    }

    public function index(Request $request) {
      $data = [];
      $group = Group::where('user_id', auth()->user()->id)->first();
      $data['social_accounts'] = SocialAccount::whereIn('id', $group->selection_list)->orderBy('created_at', 'DESC')->get();
      return view('social.index', $data);
    }

    public function destroy($id)
    {
        //
        $social = SocialAccount::find($id);
        $group = Group::where('user_id', auth()->user()->id)->first();
        if($group && in_array($id, $group->selection_list)) {
          $social->delete();
        }
        return ['status' => 'true'];
    }

}

app/Http/Controllers/Client/ReviewController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use Storage;
use Image;
use Response;
use Redirect;
use Twitter;
use Session;
use Mail;
use Artisan;
use Carbon\Carbon;
use App\Models\Review;
use App\Models\Post;
use App\Models\Group;
use App\Models\SocialAccount;
use App\Http\Requests\StoreInstagram;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Crypt;

class ReviewController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        ##$this->middleware('auth');
    }

    public function index(Request $request) {
      $group = Group::where('user_id', auth()->user()->id)->first();

      $data = [];
      $posts = Post::whereRaw('FIND_IN_SET(?,groups)', [$group->id])
                    ->whereNull('completed_at')
                    ->orderBy('created_at', 'DESC')
                    ->with(['scheduled_posts', 'scheduled_posts.social_account'])
                    ->get();
      $data['posts'] = $posts;

      return view('review.index', $data);
    }

    public function show($id)
    {
        //check if this guy can really read this post
        $group = Group::where('user_id', auth()->user()->id)->first();
        $post = Post::whereRaw('FIND_IN_SET(?,groups)', [$group->id])
                      ->where('id', $id)
                      ->first();

        $reviews = [];
        if( $post ) {
            $reviews = Review::where('post_id', $id)->with('user')->orderBy('created_at', 'DESC')->limit(10)->get();
        }

        return ['status' => 'true', 'reviews' => $reviews];
    }

    public function update($id, Request $request)
    {
        //

        $group = Group::where('user_id', auth()->user()->id)->first();
        $post = Post::whereRaw('FIND_IN_SET(?,groups)', [$group->id])
                      ->where('id', $id)
                      ->first();

        if( $post ) {
            $review = Review::create([
                'user_id' => auth()->user()->id,
                'post_id' => $id,
                'message' => $request->get('message'),
                'status' => $request->get('selection'),
            ]);

            $post->approval_status_changed_at = Carbon::now();
            if($request->get('selection') == 'approve') {
                //if approve then set the post to approved
                $post->approval_status = 'APPROVED';
                Artisan::call('warbler:schedule_queue');
            }

            if($request->get('selection') == 'request_changes') {
                //if approve then set the post to approved
                $post->approval_status = 'CHANGES_REQUESTED';
            }
            $post->save();
        }

        $post = Post::whereRaw('FIND_IN_SET(?,groups)', [$group->id])
                      ->where('id', $id)
                      ->with(['scheduled_posts', 'scheduled_posts.social_account'])
                      ->first();

        return ['status' => 'true', 'post' => $post];
    }

}

app/Http/Controllers/ClientsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Post;
use App\Models\ScheduledPost;
use App\Models\SocialAccount;
use App\Models\Group;
use App\Models\User;
use App\Http\Requests\StoreGroup;
use Kris\LaravelFormBuilder\FormBuilder;
use Hash;

class ClientsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $clients = User::orderBy('created_at', 'DESC')->paginate(15);
        return view('clients.index', ['clients' => $clients]);
    }

    public function getList()
    {
        //
        $groups = Group::orderBy('created_at', 'DESC')->get();
        return ['groups' => $groups];
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request, FormBuilder $formBuilder)
    {
        //
        $form = $formBuilder->create(\App\Forms\ClientForm::class, [
           'method' => 'POST',
           'url' => route('clients.store'),

       ]);

       return view('clients.create', compact('form'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FormBuilder $formBuilder, Request $request)
    {
        //

        $form = $formBuilder->create(\App\Forms\ClientForm::class);

        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        //test facebook token
        if($request->get('facebook_app_key')) {
          if(!$this->validFacebookToken( $request->get('facebook_app_key'), $request->get('facebook_app_secret') )) {
            $errors = [
              "facebook_app_key" => ["The Facebook app is INVALID"]
            ];
            return redirect()->back()->withErrors($errors)->withInput();
          }
        }

        //create user
        $user = User::create([
          'email' => $request->get('email'),
          'name' => $request->get('name'),
          'password' => Hash::make($request->get('password')),
        ]);
        $user->assignRole('client');

        $user->facebook_app_key = $request->get('facebook_app_key');
        $user->facebook_app_secret = $request->get('facebook_app_secret');
        $user->save();

        //create group
        $group = Group::firstOrCreate(['name' => $request->get('name')]);
        if(!$group->user_id) {
          $group->user_id = $user->id;
          $group->save();
        }
        $message = 'Successfully saved. A group was <strong>'.$request->get('name').'</strong> also created for the user.';
        if(!$group->wasRecentlyCreated) {
          $message = 'Successfully saved. User <strong>'.$request->get('name').'</strong> is using the group <strong>'.$request->get('name').'</strong>.';
        }
        return redirect('groups')->with('message', $message);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, FormBuilder $formBuilder)
    {
        //
        $form = $formBuilder->create(\App\Forms\ClientFormEdit::class, [
           'method' => 'PUT',
           'url' => route('clients.update', $id),
           'model' => User::find($id)->toArray()
        ]);

        return view('clients.edit', compact('form'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($id, FormBuilder $formBuilder, Request $request)
    {


        $form = $formBuilder->create(\App\Forms\ClientFormEdit::class);
        if (!$form->isValid()) {
            return redirect()->back()->withErrors($form->getErrors())->withInput();
        }

        $user = User::find($id);

        //test facebook token
        if($request->get('facebook_app_key')) {
          if($this->validFacebookToken( $request->get('facebook_app_key'), $request->get('facebook_app_secret') )) {
            $user->facebook_app_key = $request->get('facebook_app_key');
            $user->facebook_app_secret = $request->get('facebook_app_secret');
            $user->save();
          } else {
            $errors = [
              "facebook_app_key" => ["The Facebook app is INVALID"]
            ];
            return redirect()->back()->withErrors($errors)->withInput();
          }
        }

        if($request->get('password')) {
            $user->password = Hash::make($request->get('password'));
            $user->save();
        }

        return redirect('groups')->with('message', 'Successfully saved!');
    }

    private function validFacebookToken($app_key, $app_secret) {
      return true;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $user = User::find($id);
        $user->delete();
        return ['status' => true];
    }
}

resources/views/clients/create.blade.php
@extends('layouts.inner')
@section('title', 'Clients')

@section('inner')
<a href="<?= route('groups.index') ?>"><i class="fa fa-chevron-left" aria-hidden="true"></i> Back to accounts</a><br /><br />
<div class="panel panel-default">
    <div class="panel-body">
                  <div class="row">


                              <div class="col-sm-8 col-sm-offset-2">

                                <div class="row">


                                            <div class="col-sm-6">
											<br />
                  <h4>Adding a new client</h4>

                </div>

                <div class="col-sm-6">
                </div>
                </div>
                  <hr />

 {!! form($form, ['autocomplete' => 'new-password']) !!}
 <br />
        </div>
        </div>
        </div>

	</div>


@endsection

resources/views/clients/edit.blade.php
@extends('layouts.inner')
@section('title', 'Clients')

@section('inner')
<a href="<?= route('groups.index') ?>"><i class="fa fa-chevron-left" aria-hidden="true"></i> Back to accounts</a><br /><br />
<div class="panel panel-default">
    <div class="panel-body">
                  <div class="row">


                              <div class="col-sm-8 col-sm-offset-2">

                                <div class="row">


                                            <div class="col-sm-6">
											<br />
                  <h4>Editing new client</h4>

                </div>

                <div class="col-sm-6">
                </div>
                </div>
                  <hr />

 {!! form($form, ['autocomplete' => 'new-password']) !!}
 <br />
        </div>
        </div>
        </div>

	</div>


@endsection

resources/views/clients/index.blade.php
@extends('layouts.inner')
@section('title', 'Clients')

@section('inner')
<a href="<?= route('social-accounts.index') ?>"><i class="fa fa-chevron-left" aria-hidden="true"></i> Back to accounts</a><br /><br />
<div class="panel panel-default">
    <div class="panel-body">
                  <div class="row">


                              <div class="col-sm-12">

                                <div class="row">


                                            <div class="col-sm-6">
                  <h4>Clients</h4>

                </div>

                <div class="col-sm-6">
<a href="/clients/create" class="btn btn-default pull-right"><i class="fa fa-plus" aria-hidden="true"></i> Add new client</a>
                </div>
                </div>


                @if(session()->has('message'))
                <br />
                    <div class="alert alert-success">
                        {!! session()->get('message') !!}
                    </div>
                @endif
                  <hr />

                  <table class="table">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>Name</th>
                          <th>Email</th>
                          <th>Date Created</th>
                        </tr>
                      </thead>
                      <tbody>
                        <? foreach($clients as $client) : ?>
                        <tr>
                          <td>#<?= $client->id ?></td>
                          <td><?= $client->name ?></td>
                          <td><a href="/clients/{{$client->id}}/edit"><?= $client->email ?></a></td>
                          <td><?= $client->created_at ?></td>
                          <td><a href="#" class="delete-confirm" data-text="Deleting this account means any scheduled posts associated with it may not be posted" data-url="/clients/<?= $client->id ?>"><i class="mdi mdi-close" aria-hidden="true"></i></a></td>

                        </tr>
                        <? endforeach; ?>
                      </tbody>
                    </table>


                {{ $clients->appends($_GET)->links() }}
        </div>
        </div>
        </div>

	</div>


@endsection