routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'role:admin']], function () {
    #dd(auth()->user());
    Route::resource('groups', 'GroupsController');
    Route::resource('content', 'ContentController');
    Route::post('content/add', 'ContentController@add');
    Route::get('content/redirect/{id}', 'ContentController@redirect');
    Route::resource('feeds', 'FeedsController');
    Route::resource('queue', 'QueueController');
    Route::any('queue/listings/{type}', 'QueueController@listings');
    Route::post('queue/move/{id}', 'QueueController@move');
    Route::resource('analytics', 'AnalyticsController');
    Route::resource('schedule', 'ScheduleController');
    Route::resource('history', 'HistoryController');
    Route::resource('clients', 'ClientsController');
    Route::get('/uploads/{thumb?}', 'UploadController@getUpload')->where('thumb', '.*');
    Route::post('/upload', 'UploadController@postUpload');
    Route::get('/groups-list', 'GroupsController@getList');
    Route::get('/social-accounts-list', 'SocialController@getList');
    Route::get('/drafts', 'ContentController@getDrafts');
    Route::post('/link-preview', 'ContentController@postLinkPreview');
    Route::resource('review', 'ReviewController');
});

Route::group(['middleware' => ['auth']], function () {
  Route::get('/uploads/{thumb?}', 'UploadController@getUpload')->where('thumb', '.*');
  Route::post('/upload', 'UploadController@postUpload');
});

Route::group(['middleware' => ['auth', 'role:client']], function () {
  Route::get('/client', function () {
      return redirect('social-accounts');
  });
});

Route::group(['prefix' => 'client', 'middleware' => ['auth', 'role:client']], function()
{
    Route::resource('review', 'Client\ReviewController');
});

Route::group(['middleware' => ['auth']], function () {
  Route::resource('settings', 'SettingsController');
  Route::post('/api/upload', 'UploadController@postUpload');
  Route::resource('social-accounts', 'SocialController');
});

Route::get('/twitter/login', 'Social\TwitterController@login')->name('twitter.login');
Route::get('/twitter/callback', 'Social\TwitterController@callback')->name('twitter.callback');
Route::get('/twitter/error', 'Social\TwitterController@error')->name('twitter.error');
Route::get('/twitter/logout', 'Social\TwitterController@logout')->name('twitter.logout');

Route::get('/instagram/checkpoint', 'Social\InstagramController@getCheckpoint')->name('instagram.checkpoint');
Route::post('/instagram/checkpoint', 'Social\InstagramController@postCheckpoint')->name('instagram.post-checkpoint');
Route::resource('instagram', 'Social\InstagramController');

Route::get('/facebook/profile', 'Social\FacebookController@profile')->name('facebook.profile');
Route::get('/facebook/pages', 'Social\FacebookController@pages')->name('facebook.pages');
Route::get('/facebook/groups', 'Social\FacebookController@groups')->name('facebook.groups');
Route::get('/facebook/select/{type}/{fid}', 'Social\FacebookController@select')->name('facebook.select');
Route::get('/facebook/callback', 'Social\FacebookController@callback')->name('facebook.callback');
Route::get('/facebook/choice', 'Social\FacebookController@choice')->name('facebook.choice');
Route::get('/facebook/preselect', 'Social\FacebookController@preSelect')->name('facebook.preselect');
Route::get('/facebook/preselect/{user_id}/{select}', 'Social\FacebookController@preSelectById')->name('facebook.preselect');


Route::get('/install', 'Install\InstallController@index');
Route::get('/install/create', 'Install\InstallController@create'); // private use only
Route::get('/install/update', 'Install\InstallController@createUpdate'); // private use only
Route::get('/install/admin', 'Install\InstallController@admin');
Route::get('/install/finish', 'Install\InstallController@finish');
Route::post('/install', 'Install\InstallController@postIndex');
Route::post('/install/admin', 'Install\InstallController@postAdmin');
Route::post('/install/finish', 'Install\InstallController@postFinish');
Route::get('/install/upgrade', 'Install\InstallController@upgrade');

Route::get('/debug/phpinfo', 'DebugController@phpinfo');
Route::get('/debug/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
Route::get('/debug/cron', 'DebugController@cron');

/**
 * Teamwork routes
 */
Route::group(['prefix' => 'teams', 'namespace' => 'Teamwork'], function()
{
    Route::get('/', 'TeamController@index')->name('teams.index');
    Route::get('create', 'TeamController@create')->name('teams.create');
    Route::post('teams', 'TeamController@store')->name('teams.store');
    Route::get('edit/{id}', 'TeamController@edit')->name('teams.edit');
    Route::put('edit/{id}', 'TeamController@update')->name('teams.update');
    Route::delete('destroy/{id}', 'TeamController@destroy')->name('teams.destroy');
    Route::get('switch/{id}', 'TeamController@switchTeam')->name('teams.switch');

    Route::get('members/{id}', 'TeamMemberController@show')->name('teams.members.show');
    Route::get('members/resend/{invite_id}', 'TeamMemberController@resendInvite')->name('teams.members.resend_invite');
    Route::post('members/{id}', 'TeamMemberController@invite')->name('teams.members.invite');
    Route::delete('members/{id}/{user_id}', 'TeamMemberController@destroy')->name('teams.members.destroy');

    Route::get('accept/{token}', 'AuthController@acceptInvite')->name('teams.accept_invite');
});

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
  protected $fillable = ['key', 'value'];

}

app/Http/Controllers/SettingsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Setting;
use App\Models\User;
use Validator;
use Auth;
use Hash;
use Jackiedo\DotenvEditor\Facades\DotenvEditor;

class SettingsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $tzlist = \DateTimeZone::listIdentifiers(\DateTimeZone::ALL);
        $data = [];
        $data['tzlist'] = array_combine($tzlist, $tzlist);
        $data['current_tz'] = config('app.timezone');
        $data['proxy'] = "";
        $data['link_shortening'] = false;

        $proxy = Setting::where('key', 'proxy')->first();
        if($proxy)
            $data['proxy'] = $proxy->value;

        $link_shortening = Setting::where('key', 'link_shortening')->first();
        if($link_shortening)
            $data['link_shortening'] = $link_shortening->value;

        $link_shortening = Setting::where('key', 'link_shortening')->first();
        if($link_shortening)
            $data['link_shortening'] = $link_shortening->value;

        return view('settings.index', $data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if($request->exists('timezone')) {          
          //change .env
          $file = DotenvEditor::setKey('TIMEZONE', $request->get('timezone'));
          $file = DotenvEditor::save();

          return redirect('settings')->with('message', 'Successfully updated!');
        }

        if($request->exists('proxy')) {
          Setting::updateOrCreate(
            ['key' => 'proxy'],
            ['value' => $request->get('proxy')]
          );
          return redirect('settings')->with('message', 'Successfully updated!');
        }

        if($request->exists('password') || $request->exists('confirm_password')) {

          if(env('DEMO')) {
            return view('errors.disabled');
          }

          $request_data = $request->all();

           $validator = $this->admin_credential_rules($request_data);
           if($validator->fails()) {
             return redirect('settings')->withErrors(['Error - Password do not match']);
          } else {
            $user_id = Auth::User()->id;
            $user = User::find(Auth::User()->id);
            $user->password = Hash::make($request->get('password'));
            $user->save();
            return redirect('settings')->with('message', 'Successfully updated!');
          }
        }
        return redirect('settings');
    }

    private function admin_credential_rules(array $data)
{
  $messages = [
    'confirm_password.required' => 'Please enter current password',
    'password.required' => 'Please enter password',
  ];

  $validator = Validator::make($data, [
    'password' => 'required|same:password',
    'confirm_password' => 'required|same:password',
  ], $messages);

  return $validator;
}

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/settings/index.blade.php
@extends('layouts.inner')
@section('title', 'Settings')

@section('inner')


          <div class="row">

            <div class="col-md-12">
              <br />
              @if(session()->has('message'))
                  <div class="alert alert-success">
                      {{ session()->get('message') }}
                  </div>
              @endif

              @foreach ($errors->all() as $error)

                <div class="alert alert-danger">{{ $error }}</div>

              @endforeach

              <div class="panel panel-default">
              <div class="panel-body">
                <div class="row">

                  <div class="col-md-5">
<h4 id="password">Change password</h4>
<p>Great passwords use lower and uppercase characters, numbers and symbols such as !"$£%&. Make sure you remember it.</p>
                    </div>

                  <div class="col-md-7">
                    <form method="POST" action="<?= route('settings.store') ?>">
                      {{ csrf_field() }}
                      <div class="form-group">
                        <label for="exampleInputEmail1">Email</label>
                        <input type="email" class="form-control" name="email" placeholder="" value="<?= auth()->user()->email ?>" disabled>
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">New password</label>
                        <input type="password" class="form-control" name="password" placeholder="">
                      </div>
                      <div class="form-group">
                        <label for="exampleInputPassword1">Confirm new password</label>
                        <input type="password" class="form-control" name="confirm_password" placeholder="">
                      </div>
                      <button type="submit" class="btn btn-primary">save</button>
                    </form>
                    </div>

                    </div>
                    </div>
                    </div>

                    @hasrole('admin')

                <hr />
                <div class="panel panel-default">
                <div class="panel-body">
                <div class="row">

                  <div class="col-md-5">
<h4 id="time">Time &amp; Date</h4>
<p>Select the timezone you want to post from.</p>
                    </div>

                  <div class="col-md-7">
                    <form method="POST" action="<?= route('settings.store') ?>">
                      {{ csrf_field() }}
                      <div class="form-group">
                        <label for="exampleInputEmail1">Timezone region</label>

                        {{ Form::select('timezone', $tzlist, $current_tz, ['class' => 'form-control']) }}
                      </div>
                      <button type="submit" class="btn btn-primary">save</button>
                    </form>
                    </div>

                    </div>
                    </div>
                    </div>
                    @endhasrole



                      <br />  <br />
                      <br />  <br />
                      <br />  <br />



</div>



            </div>


@endsection